import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";




const Inter = localFont({
  src: './Fonts/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter'
})

const Boska = localFont({
  src: './Fonts/Boska-Variable.ttf',
  variable: '--font-boska'
})


export const metadata: Metadata = {
  title: "McDonald's Reimagined",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Boska.variable} ${Inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
