import type { Metadata } from "next";
import localFont from 'next/font/local'
import Footer from "./Sections/Footer";
import "./globals.css";


const Vogue = localFont({
  src: './Fonts/Vogue.ttf',
  variable: '--font-vogue'
})

const Jost = localFont({
  src: './Fonts/Jost-VariableFont_wght.ttf',
  variable: '--font-jost'
})


export const metadata: Metadata = {
  title: "McDonald's Reimagined",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <html lang="en">
      <body className={`${Vogue.variable} ${Jost.variable}`}
      >
        {children}
      </body>
    </html>
    <Footer/>
    </>
  );
}
