export const clothing_items = [
  {
    id: 'bomber-jacket-001',
    img: '/clothing/bomber_1.png',
    hover: '/clothing/bomber_2.png',
    gallery: [
      '/clothing/bomber_1.png',
      '/clothing/bomber_2.png',
    ],
    item: 'Bomber Jacket',
    slug: 'bomber-jacket',
    category: 'Outerwear',
    tags: ['jacket', 'outerwear', 'casual', 'streetwear'],
    price: 1200,
    compareAtPrice: 1500,
    currency: 'ZAR',
    sku: 'BJ-001-BLK',
    description:
      'A modern take on the classic bomber silhouette. Cut from a water-resistant shell with a satin lining and ribbed trim at the cuffs, collar and hem.',
    details: [
      'Water-resistant outer shell',
      'Satin lining',
      'Ribbed collar, cuffs & hem',
      'Two side zip pockets',
      'One interior zip pocket',
      'Metal YKK zipper',
    ],
    careInstructions: ['Machine wash cold', 'Do not tumble dry', 'Iron on low'],
    material: '100% Nylon shell, 100% Polyester lining',
    origin: 'Made in Portugal',
    fit: 'Regular fit — model is 188 cm and wears size M',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableSizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/bomber_1.png' },
      { name: 'Olive', hex: '#6b6b3a', img: '/clothing/bomber_olive_1.png' },
      { name: 'Navy', hex: '#1b2a4a', img: '/clothing/bomber_navy_1.png' },
    ],
    selectedColor: 'Black',
    rating: 4.6,
    reviewCount: 128,
    isNew: false,
    isBestseller: true,
    isSale: true,
    inStock: true,
    stockCount: 14,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['sweater-001', 'cap-001', 'belt-001'],
  },
  {
    id: 'sweater-001',
    img: '/clothing/sweater_1.png',
    hover: '/clothing/sweater_2.png',
    gallery: [
      '/clothing/sweater_1.png',
      '/clothing/sweater_2.png',
    ],
    item: 'Sweater',
    slug: 'crewneck-sweater',
    category: 'Knitwear',
    tags: ['knit', 'sweater', 'casual', 'winter'],
    price: 800,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'SW-001-ECR',
    description:
      'A heavyweight crewneck knit in a loose-gauge cotton blend. Understated and versatile — easy to layer or wear on its own.',
    details: [
      'Heavyweight loose-gauge knit',
      'Drop shoulder construction',
      'Ribbed crewneck, cuffs & hem',
      'Slightly oversized fit',
    ],
    careInstructions: ['Hand wash cold', 'Lay flat to dry', 'Do not bleach'],
    material: '80% Cotton, 20% Wool',
    origin: 'Made in Turkey',
    fit: 'Oversized — model is 188 cm and wears size S',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Ecru', hex: '#f5f0e8', img: '/clothing/sweater_1.png' },
      { name: 'Charcoal', hex: '#3a3a3a', img: '/clothing/sweater_charcoal_1.png' },
    ],
    selectedColor: 'Ecru',
    rating: 4.8,
    reviewCount: 74,
    isNew: true,
    isBestseller: false,
    isSale: false,
    inStock: true,
    stockCount: 32,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['bomber-jacket-001', 'blazer-001', 'beanie-001'],
  },
  {
    id: 'blazer-001',
    img: '/clothing/blazer_1.png',
    hover: '/clothing/blazer_2.png',
    gallery: [
      '/clothing/blazer_1.png',
      '/clothing/blazer_2.png',
    ],
    item: 'Blazer',
    slug: 'structured-blazer',
    category: 'Tailoring',
    tags: ['blazer', 'tailoring', 'formal', 'smart-casual'],
    price: 1500,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'BL-001-SNT',
    description:
      'A precisely tailored single-breasted blazer with a slim, structured silhouette. Transitions seamlessly from the office to an evening out.',
    details: [
      'Single-breasted, two-button closure',
      'Notch lapel',
      'Two flap pockets at hip',
      'One welt breast pocket',
      'Three-button surgeon cuffs',
      'Half-canvas construction',
    ],
    careInstructions: ['Dry clean only'],
    material: '55% Wool, 45% Polyester',
    origin: 'Made in Italy',
    fit: 'Slim fit — model is 188 cm and wears size 48',
    sizes: ['44', '46', '48', '50', '52', '54'],
    availableSizes: ['46', '48', '50', '52'],
    colors: [
      { name: 'Stone', hex: '#c8b99a', img: '/clothing/blazer_1.png' },
      { name: 'Navy', hex: '#1b2a4a', img: '/clothing/blazer_navy_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/blazer_black_1.png' },
    ],
    selectedColor: 'Stone',
    rating: 4.5,
    reviewCount: 52,
    isNew: false,
    isBestseller: false,
    isSale: false,
    inStock: true,
    stockCount: 9,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['belt-001', 'sweater-001'],
  },
  {
    id: 'belt-001',
    img: '/clothing/belt_1.png',
    hover: '/clothing/belt_2.png',
    gallery: [
      '/clothing/belt_1.png',
      '/clothing/belt_2.png',
    ],
    item: 'Belt',
    slug: 'leather-belt',
    category: 'Accessories',
    tags: ['belt', 'leather', 'accessories', 'formal'],
    price: 400,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'BT-001-TAN',
    description:
      'A full-grain leather belt with a solid brass pin buckle. Simple, durable, and built to develop a rich patina over time.',
    details: [
      'Full-grain leather',
      'Solid brass pin buckle',
      'Width: 3.5 cm',
      '5 adjustment holes',
    ],
    careInstructions: ['Wipe with damp cloth', 'Condition with leather balm periodically'],
    material: '100% Full-grain leather',
    origin: 'Made in South Africa',
    fit: 'Order your trouser waist size — available in 2 cm increments',
    sizes: ['75', '80', '85', '90', '95', '100'],
    availableSizes: ['75', '80', '85', '90', '95', '100'],
    colors: [
      { name: 'Tan', hex: '#c19a6b', img: '/clothing/belt_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/belt_black_1.png' },
    ],
    selectedColor: 'Tan',
    rating: 4.9,
    reviewCount: 203,
    isNew: false,
    isBestseller: true,
    isSale: false,
    inStock: true,
    stockCount: 60,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['blazer-001', 'bomber-jacket-001'],
  },
  {
    id: 'tote-001',
    img: '/clothing/tote_1.png',
    hover: '/clothing/tote_2.png',
    gallery: [
      '/clothing/tote_1.png',
      '/clothing/tote_2.png',
    ],
    item: 'Tote Bag',
    slug: 'canvas-tote-bag',
    category: 'Bags',
    tags: ['tote', 'bag', 'canvas', 'accessories'],
    price: 600,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'TT-001-NAT',
    description:
      'A generous, heavy-duty canvas tote with reinforced handles and an internal zip pocket. Practical without sacrificing style.',
    details: [
      'Heavy 12 oz canvas',
      'Reinforced stitching at handles',
      'Internal zip pocket',
      'Magnetic snap closure',
      'Dimensions: 40 × 35 × 12 cm',
      'Handle drop: 28 cm',
    ],
    careInstructions: ['Machine wash cold', 'Air dry', 'Do not iron'],
    material: '100% Cotton canvas',
    origin: 'Made in India',
    fit: null,
    sizes: ['One Size'],
    availableSizes: ['One Size'],
    colors: [
      { name: 'Natural', hex: '#e8dcc8', img: '/clothing/tote_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/tote_black_1.png' },
    ],
    selectedColor: 'Natural',
    rating: 4.7,
    reviewCount: 89,
    isNew: false,
    isBestseller: false,
    isSale: false,
    inStock: true,
    stockCount: 45,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['bag-001', 'bracelet-001'],
  },
  {
    id: 'bag-001',
    img: '/clothing/bag_1.png',
    hover: '/clothing/bag_2.png',
    gallery: [
      '/clothing/bag_1.png',
      '/clothing/bag_2.png',
    ],
    item: 'Bag',
    slug: 'leather-shoulder-bag',
    category: 'Bags',
    tags: ['bag', 'leather', 'shoulder bag', 'accessories'],
    price: 900,
    compareAtPrice: 1100,
    currency: 'ZAR',
    sku: 'BG-001-BRN',
    description:
      'A compact leather shoulder bag with a structured silhouette. Fits all your daily essentials with room to spare.',
    details: [
      'Pebbled leather exterior',
      'Suede lining',
      'Adjustable shoulder strap (50–90 cm drop)',
      'Two exterior slip pockets',
      'Three interior card slots',
      'Dimensions: 28 × 20 × 8 cm',
      'Gold-tone hardware',
    ],
    careInstructions: [
      'Wipe with dry cloth',
      'Store stuffed with tissue to maintain shape',
      'Keep away from direct sunlight',
    ],
    material: '100% Pebbled leather',
    origin: 'Made in Spain',
    fit: null,
    sizes: ['One Size'],
    availableSizes: ['One Size'],
    colors: [
      { name: 'Brown', hex: '#8b5e3c', img: '/clothing/bag_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/bag_black_1.png' },
      { name: 'Tan', hex: '#c19a6b', img: '/clothing/bag_tan_1.png' },
    ],
    selectedColor: 'Brown',
    rating: 4.4,
    reviewCount: 37,
    isNew: false,
    isBestseller: false,
    isSale: true,
    inStock: true,
    stockCount: 6,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['tote-001', 'belt-001'],
  },
  {
    id: 'bracelet-001',
    img: '/clothing/bracelet_1.png',
    hover: '/clothing/bracelet_2.png',
    gallery: [
      '/clothing/bracelet_1.png',
      '/clothing/bracelet_2.png',
    ],
    item: 'Bracelet',
    slug: 'beaded-bracelet',
    category: 'Jewellery',
    tags: ['bracelet', 'jewellery', 'accessories', 'unisex'],
    price: 300,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'BR-001-BLK',
    description:
      'Hand-strung matte onyx beads on an elastic cord. Minimalist, unisex, and easy to stack.',
    details: [
      'Matte onyx beads, 8 mm diameter',
      'Elastic cord — one size fits most',
      'Circumference: approx. 19 cm',
      'Handmade',
    ],
    careInstructions: ['Avoid contact with water', 'Store in a cool dry place'],
    material: 'Natural onyx, elastic cord',
    origin: 'Handmade in South Africa',
    fit: 'One size fits most wrists 15–20 cm',
    sizes: ['One Size'],
    availableSizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/bracelet_1.png' },
      { name: 'Sand', hex: '#d4b896', img: '/clothing/bracelet_sand_1.png' },
    ],
    selectedColor: 'Black',
    rating: 4.8,
    reviewCount: 156,
    isNew: false,
    isBestseller: true,
    isSale: false,
    inStock: true,
    stockCount: 80,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['cap-001', 'tote-001'],
  },
  {
    id: 'cap-001',
    img: '/clothing/cap_1.png',
    hover: '/clothing/cap_2.png',
    gallery: [
      '/clothing/cap_1.png',
      '/clothing/cap_2.png',
    ],
    item: 'Cap',
    slug: 'six-panel-cap',
    category: 'Headwear',
    tags: ['cap', 'hat', 'headwear', 'casual', 'streetwear'],
    price: 350,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'CP-001-WHT',
    description:
      'A clean six-panel structured cap with a pre-curved brim. No logos, no fuss — just a well-made staple.',
    details: [
      'Six-panel structured crown',
      'Pre-curved brim',
      'Adjustable strapback closure',
      'Embroidered eyelet ventilation',
      'Sweatband: 100% cotton',
    ],
    careInstructions: ['Hand wash cold', 'Reshape and air dry', 'Do not machine wash'],
    material: '100% Brushed cotton twill',
    origin: 'Made in Bangladesh',
    fit: 'Adjustable — fits head circumference 54–60 cm',
    sizes: ['One Size'],
    availableSizes: ['One Size'],
    colors: [
      { name: 'White', hex: '#f5f5f0', img: '/clothing/cap_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/cap_black_1.png' },
      { name: 'Khaki', hex: '#b5a88a', img: '/clothing/cap_khaki_1.png' },
    ],
    selectedColor: 'White',
    rating: 4.6,
    reviewCount: 91,
    isNew: true,
    isBestseller: false,
    isSale: false,
    inStock: true,
    stockCount: 55,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['beanie-001', 'bracelet-001', 'bomber-jacket-001'],
  },
  {
    id: 'beanie-001',
    img: '/clothing/beanie_1.png',
    hover: '/clothing/beanie_2.png',
    gallery: [
      '/clothing/beanie_1.png',
      '/clothing/beanie_2.png',
    ],
    item: 'Beanie',
    slug: 'ribbed-beanie',
    category: 'Headwear',
    tags: ['beanie', 'hat', 'headwear', 'winter', 'knit'],
    price: 300,
    compareAtPrice: null,
    currency: 'ZAR',
    sku: 'BN-001-GRY',
    description:
      'A classic fine-ribbed beanie knit in a merino wool blend. Warm without the bulk, and soft enough to wear all day.',
    details: [
      'Fine 1×1 rib knit',
      'Folded cuff',
      'Stretches to fit most head sizes',
      'Unisex fit',
    ],
    careInstructions: ['Hand wash cold', 'Lay flat to dry', 'Do not tumble dry'],
    material: '60% Merino wool, 40% Acrylic',
    origin: 'Made in Scotland',
    fit: 'One size — circumference approx. 54–60 cm',
    sizes: ['One Size'],
    availableSizes: ['One Size'],
    colors: [
      { name: 'Grey', hex: '#9a9a9a', img: '/clothing/beanie_1.png' },
      { name: 'Cream', hex: '#f5f0e8', img: '/clothing/beanie_cream_1.png' },
      { name: 'Black', hex: '#1a1a1a', img: '/clothing/beanie_black_1.png' },
      { name: 'Forest', hex: '#3a5a40', img: '/clothing/beanie_forest_1.png' },
    ],
    selectedColor: 'Grey',
    rating: 4.9,
    reviewCount: 214,
    isNew: false,
    isBestseller: true,
    isSale: false,
    inStock: true,
    stockCount: 110,
    shippingInfo: 'Free shipping on orders over R1,000. Delivery in 3–5 business days.',
    returnPolicy: '30-day free returns on unworn items with original tags.',
    relatedProducts: ['cap-001', 'sweater-001', 'bomber-jacket-001'],
  },
]